WebProject/Controllers/ContoraController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebProject.Data;
using WebProject.Data.Entity;
using WebProject.Models;

namespace WebProject.Controllers
{
    public class ContoraController : Controller
    {
        private readonly DataDbContext _db;

        public ContoraController(DataDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            IEnumerable<Contora> objList = _db.Contoras;
            return View(objList);

        }

        // GET-Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST-Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public IActionResult Create(Contora obj)
        {
            if (ModelState.IsValid)
            {
                _db.Contoras.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);

        }


        // GET Delete
        [Authorize(Roles = "admin")]
        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Contoras.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        // POST Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Contoras.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Contoras.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

        // GET Update
        [Authorize(Roles = "admin, moderator")]
        public IActionResult Update(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Contoras.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        // POST UPDATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, moderator")]
        public IActionResult Update(Contora obj)
        {
            if (ModelState.IsValid)
            {
                _db.Contoras.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

WebProject/Views/Contora/Create.cshtml
@model WebProject.Data.Entity.Contora

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Добавить контору</h2>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Street" class="control-label"></label>
                    <input asp-for="Street" class="form-control" />
                    <span asp-validation-for="Street" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="House" class="control-label"></label>
                    <input asp-for="House" class="form-control" />
                    <span asp-validation-for="House" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    <div class="col-12 row">
                        <div class="col-4">
                            <input type="submit" class="btn btn-success w-150" value="Создать" />
                        </div>
                        <div class="col-4">
                            <a asp-action="Index" class="btn btn-info w-150">Вернуться</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WebProject/Views/Contora/Delete.cshtml
@model WebProject.Data.Entity.Contora

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Удалить контору</h2>
        </div>
        <div class="row">
            <div class="col-md-5">
                <div class="form-group row">
                    <div class="col-5">
                        <label asp-for="City"></label>
                        <input asp-for="City" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-12 row">
                        <div class="col-3">
                            <input type="submit" class="btn btn-danger w-150" value="Удалить" />
                        </div>
                        <div class="col-3">
                            <a asp-action="Index" class="btn btn-info w-150">Вернуться</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WebProject/Views/Contora/Index.cshtml
@model IEnumerable<WebProject.Data.Entity.Contora>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-dark">Список контор</h2>
        </div>
        @if (User.IsInRole("admin") || User.IsInRole("moderator"))
        {
            <div class="col-6 text-right">
                <a asp-controller="Contora" asp-action="Create" class="btn btn-primary">Создать "контору"</a>
            </div>
        }
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Город
                    </th>
                    <th>
                        Улица
                    </th>
                    <th>
                        Номер дома
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var contora in Model)
                {
                <tr>
                    <td width="25%">@contora.City</td>
                    <td width="25%">@contora.Street</td>
                    <td width="25%">@contora.House</td>
                    @if (User.IsInRole("admin") || User.IsInRole("moderator"))
                    {
                        <td width="25%">
                            <div class="w-100 btn-group" role="group">
                                <a asp-controller="Contora" asp-action="Update" asp-route-Id="@contora.Id" class="btn btn-success mx-1">Изменить</a>
                                <a asp-controller="Contora" asp-action="Delete" asp-route-Id="@contora.Id" class="btn btn-danger mx-1">Удалить</a>
                            </div>
                        </td>
                    }
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No items created yet</p>
    }

</div>

WebProject/Views/Contora/Update.cshtml
@model WebProject.Data.Entity.Contora

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">

        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Изменение информации о конторе</h2>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Street" class="control-label"></label>
                    <input asp-for="Street" class="form-control" />
                    <span asp-validation-for="Street" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="House" class="control-label"></label>
                    <input asp-for="House" class="form-control" />
                    <span asp-validation-for="House" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    <div class="col-12 row">
                        <div class="col-5">
                            <input type="submit" class="btn btn-success w-150" value="Подтвердить" />
                        </div>
                        <div class="col-4">
                            <a asp-action="Index" class="btn btn-info w-150">Вернуться</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}